<?php

declare(strict_types=1);

namespace PaylineWebPayment;

/**
 * Class which returns the class map definition
 */
class ClassMap
{
    /**
     * Returns the mapping between the WSDL Structs and generated Structs' classes
     * This array is sent to the \SoapClient when calling the WS
     * @return string[]
     */
    final public static function get(): array
    {
        return [
            'doWebPaymentRequest' => 'PaylineWebPayment\\StructType\\DoWebPaymentRequest',
            'doWebPaymentResponse' => 'PaylineWebPayment\\StructType\\DoWebPaymentResponse',
            'getWebPaymentDetailsRequest' => 'PaylineWebPayment\\StructType\\GetWebPaymentDetailsRequest',
            'getWebPaymentDetailsResponse' => 'PaylineWebPayment\\StructType\\GetWebPaymentDetailsResponse',
            'doAuthorizationRequest' => 'PaylineWebPayment\\StructType\\DoAuthorizationRequest',
            'doAuthorizationResponse' => 'PaylineWebPayment\\StructType\\DoAuthorizationResponse',
            'doCaptureRequest' => 'PaylineWebPayment\\StructType\\DoCaptureRequest',
            'doCaptureResponse' => 'PaylineWebPayment\\StructType\\DoCaptureResponse',
            'doDebitRequest' => 'PaylineWebPayment\\StructType\\DoDebitRequest',
            'doDebitResponse' => 'PaylineWebPayment\\StructType\\DoDebitResponse',
            'doRefundRequest' => 'PaylineWebPayment\\StructType\\DoRefundRequest',
            'doRefundResponse' => 'PaylineWebPayment\\StructType\\DoRefundResponse',
            'doResetRequest' => 'PaylineWebPayment\\StructType\\DoResetRequest',
            'doResetResponse' => 'PaylineWebPayment\\StructType\\DoResetResponse',
            'doCreditRequest' => 'PaylineWebPayment\\StructType\\DoCreditRequest',
            'doCreditResponse' => 'PaylineWebPayment\\StructType\\DoCreditResponse',
            'createWalletRequest' => 'PaylineWebPayment\\StructType\\CreateWalletRequest',
            'createWalletResponse' => 'PaylineWebPayment\\StructType\\CreateWalletResponse',
            'updateWalletRequest' => 'PaylineWebPayment\\StructType\\UpdateWalletRequest',
            'updateWalletResponse' => 'PaylineWebPayment\\StructType\\UpdateWalletResponse',
            'getWalletRequest' => 'PaylineWebPayment\\StructType\\GetWalletRequest',
            'getWalletResponse' => 'PaylineWebPayment\\StructType\\GetWalletResponse',
            'getCardsRequest' => 'PaylineWebPayment\\StructType\\GetCardsRequest',
            'getCardsResponse' => 'PaylineWebPayment\\StructType\\GetCardsResponse',
            'disableWalletRequest' => 'PaylineWebPayment\\StructType\\DisableWalletRequest',
            'disableWalletResponse' => 'PaylineWebPayment\\StructType\\DisableWalletResponse',
            'enableWalletRequest' => 'PaylineWebPayment\\StructType\\EnableWalletRequest',
            'enableWalletResponse' => 'PaylineWebPayment\\StructType\\EnableWalletResponse',
            'doImmediateWalletPaymentRequest' => 'PaylineWebPayment\\StructType\\DoImmediateWalletPaymentRequest',
            'doImmediateWalletPaymentResponse' => 'PaylineWebPayment\\StructType\\DoImmediateWalletPaymentResponse',
            'doScheduledWalletPaymentRequest' => 'PaylineWebPayment\\StructType\\DoScheduledWalletPaymentRequest',
            'doScheduledWalletPaymentResponse' => 'PaylineWebPayment\\StructType\\DoScheduledWalletPaymentResponse',
            'doRecurrentWalletPaymentRequest' => 'PaylineWebPayment\\StructType\\DoRecurrentWalletPaymentRequest',
            'doRecurrentWalletPaymentResponse' => 'PaylineWebPayment\\StructType\\DoRecurrentWalletPaymentResponse',
            'getPaymentRecordRequest' => 'PaylineWebPayment\\StructType\\GetPaymentRecordRequest',
            'getPaymentRecordResponse' => 'PaylineWebPayment\\StructType\\GetPaymentRecordResponse',
            'disablePaymentRecordRequest' => 'PaylineWebPayment\\StructType\\DisablePaymentRecordRequest',
            'disablePaymentRecordResponse' => 'PaylineWebPayment\\StructType\\DisablePaymentRecordResponse',
            'manageWebWalletRequest' => 'PaylineWebPayment\\StructType\\ManageWebWalletRequest',
            'manageWebWalletResponse' => 'PaylineWebPayment\\StructType\\ManageWebWalletResponse',
            'createWebWalletRequest' => 'PaylineWebPayment\\StructType\\CreateWebWalletRequest',
            'createWebWalletResponse' => 'PaylineWebPayment\\StructType\\CreateWebWalletResponse',
            'updateWebWalletRequest' => 'PaylineWebPayment\\StructType\\UpdateWebWalletRequest',
            'updateWebWalletResponse' => 'PaylineWebPayment\\StructType\\UpdateWebWalletResponse',
            'getWebWalletRequest' => 'PaylineWebPayment\\StructType\\GetWebWalletRequest',
            'getWebWalletResponse' => 'PaylineWebPayment\\StructType\\GetWebWalletResponse',
            'doAuthorizationRedirectRequest' => 'PaylineWebPayment\\StructType\\DoAuthorizationRedirectRequest',
            'doAuthorizationRedirectResponse' => 'PaylineWebPayment\\StructType\\DoAuthorizationRedirectResponse',
            'getTransactionDetailsRequest' => 'PaylineWebPayment\\StructType\\GetTransactionDetailsRequest',
            'getTransactionDetailsResponse' => 'PaylineWebPayment\\StructType\\GetTransactionDetailsResponse',
            'transactionsSearchRequest' => 'PaylineWebPayment\\StructType\\TransactionsSearchRequest',
            'transactionsSearchResponse' => 'PaylineWebPayment\\StructType\\TransactionsSearchResponse',
            'verifyEnrollmentRequest' => 'PaylineWebPayment\\StructType\\VerifyEnrollmentRequest',
            'verifyEnrollmentResponse' => 'PaylineWebPayment\\StructType\\VerifyEnrollmentResponse',
            'verifyAuthenticationRequest' => 'PaylineWebPayment\\StructType\\VerifyAuthenticationRequest',
            'verifyAuthenticationResponse' => 'PaylineWebPayment\\StructType\\VerifyAuthenticationResponse',
            'doScoringChequeRequest' => 'PaylineWebPayment\\StructType\\DoScoringChequeRequest',
            'doScoringChequeResponse' => 'PaylineWebPayment\\StructType\\DoScoringChequeResponse',
            'getEncryptionKeyRequest' => 'PaylineWebPayment\\StructType\\GetEncryptionKeyRequest',
            'getEncryptionKeyResponse' => 'PaylineWebPayment\\StructType\\GetEncryptionKeyResponse',
            'doReAuthorizationRequest' => 'PaylineWebPayment\\StructType\\DoReAuthorizationRequest',
            'doReAuthorizationResponse' => 'PaylineWebPayment\\StructType\\DoReAuthorizationResponse',
            'getMerchantSettingsRequest' => 'PaylineWebPayment\\StructType\\GetMerchantSettingsRequest',
            'getMerchantSettingsResponse' => 'PaylineWebPayment\\StructType\\GetMerchantSettingsResponse',
            'listPointOfSell' => 'PaylineWebPayment\\StructType\\ListPointOfSell',
            'getBalanceRequest' => 'PaylineWebPayment\\StructType\\GetBalanceRequest',
            'getBalanceResponse' => 'PaylineWebPayment\\StructType\\GetBalanceResponse',
            'balance' => 'PaylineWebPayment\\StructType\\Balance',
            'getAlertDetailsRequest' => 'PaylineWebPayment\\StructType\\GetAlertDetailsRequest',
            'getAlertDetailsResponse' => 'PaylineWebPayment\\StructType\\GetAlertDetailsResponse',
            'getTokenRequest' => 'PaylineWebPayment\\StructType\\GetTokenRequest',
            'getTokenResponse' => 'PaylineWebPayment\\StructType\\GetTokenResponse',
            'unBlockRequest' => 'PaylineWebPayment\\StructType\\UnBlockRequest',
            'unBlockResponse' => 'PaylineWebPayment\\StructType\\UnBlockResponse',
            'updatePaymentRecordRequest' => 'PaylineWebPayment\\StructType\\UpdatePaymentRecordRequest',
            'updatePaymentRecordResponse' => 'PaylineWebPayment\\StructType\\UpdatePaymentRecordResponse',
            'getBillingRecordRequest' => 'PaylineWebPayment\\StructType\\GetBillingRecordRequest',
            'getBillingRecordResponse' => 'PaylineWebPayment\\StructType\\GetBillingRecordResponse',
            'updateBillingRecordRequest' => 'PaylineWebPayment\\StructType\\UpdateBillingRecordRequest',
            'updateBillingRecordResponse' => 'PaylineWebPayment\\StructType\\UpdateBillingRecordResponse',
            'doBankTransferRequest' => 'PaylineWebPayment\\StructType\\DoBankTransferRequest',
            'doBankTransferResponse' => 'PaylineWebPayment\\StructType\\DoBankTransferResponse',
            'isRegisteredRequest' => 'PaylineWebPayment\\StructType\\IsRegisteredRequest',
            'isRegisteredResponse' => 'PaylineWebPayment\\StructType\\IsRegisteredResponse',
            'prepareSessionRequest' => 'PaylineWebPayment\\StructType\\PrepareSessionRequest',
            'prepareSessionResponse' => 'PaylineWebPayment\\StructType\\PrepareSessionResponse',
            'result' => 'PaylineWebPayment\\StructType\\Result',
            'cardOut' => 'PaylineWebPayment\\StructType\\CardOut',
            'extendedCardType' => 'PaylineWebPayment\\StructType\\ExtendedCardType',
            'order' => 'PaylineWebPayment\\StructType\\Order',
            'key' => 'PaylineWebPayment\\StructType\\Key',
            'details' => 'PaylineWebPayment\\StructType\\Details',
            'orderDetail' => 'PaylineWebPayment\\StructType\\OrderDetail',
            'privateData' => 'PaylineWebPayment\\StructType\\PrivateData',
            'miscDataPair' => 'PaylineWebPayment\\StructType\\MiscDataPair',
            'transaction' => 'PaylineWebPayment\\StructType\\Transaction',
            'scoring' => 'PaylineWebPayment\\StructType\\Scoring',
            'fraudResultDetails' => 'PaylineWebPayment\\StructType\\FraudResultDetails',
            'payment' => 'PaylineWebPayment\\StructType\\Payment',
            'authorization' => 'PaylineWebPayment\\StructType\\Authorization',
            'paymentData' => 'PaylineWebPayment\\StructType\\PaymentData',
            'card' => 'PaylineWebPayment\\StructType\\Card',
            'buyer' => 'PaylineWebPayment\\StructType\\Buyer',
            'owner' => 'PaylineWebPayment\\StructType\\Owner',
            'address' => 'PaylineWebPayment\\StructType\\Address',
            'addressOwner' => 'PaylineWebPayment\\StructType\\AddressOwner',
            'capture' => 'PaylineWebPayment\\StructType\\Capture',
            'refund' => 'PaylineWebPayment\\StructType\\Refund',
            'selectedContractList' => 'PaylineWebPayment\\StructType\\SelectedContractList',
            'privateDataList' => 'PaylineWebPayment\\StructType\\PrivateDataList',
            'miscData' => 'PaylineWebPayment\\StructType\\MiscData',
            'avs' => 'PaylineWebPayment\\StructType\\Avs',
            'contractNumberWalletList' => 'PaylineWebPayment\\StructType\\ContractNumberWalletList',
            'cardsList' => 'PaylineWebPayment\\StructType\\CardsList',
            'captureAuthorizationList' => 'PaylineWebPayment\\StructType\\CaptureAuthorizationList',
            'refundAuthorizationList' => 'PaylineWebPayment\\StructType\\RefundAuthorizationList',
            'resetAuthorizationList' => 'PaylineWebPayment\\StructType\\ResetAuthorizationList',
            'failedListObject' => 'PaylineWebPayment\\StructType\\FailedListObject',
            'failedObject' => 'PaylineWebPayment\\StructType\\FailedObject',
            'recurring' => 'PaylineWebPayment\\StructType\\Recurring',
            'recurringForUpdate' => 'PaylineWebPayment\\StructType\\RecurringForUpdate',
            'billingRecord' => 'PaylineWebPayment\\StructType\\BillingRecord',
            'billingRecordList' => 'PaylineWebPayment\\StructType\\BillingRecordList',
            'billingRecordForUpdate' => 'PaylineWebPayment\\StructType\\BillingRecordForUpdate',
            'wallet' => 'PaylineWebPayment\\StructType\\Wallet',
            'cards' => 'PaylineWebPayment\\StructType\\Cards',
            'walletIdList' => 'PaylineWebPayment\\StructType\\WalletIdList',
            'transactionList' => 'PaylineWebPayment\\StructType\\TransactionList',
            'authentication3DSecure' => 'PaylineWebPayment\\StructType\\Authentication3DSecure',
            'connectionData' => 'PaylineWebPayment\\StructType\\ConnectionData',
            'scoringCheque' => 'PaylineWebPayment\\StructType\\ScoringCheque',
            'addressInterlocutor' => 'PaylineWebPayment\\StructType\\AddressInterlocutor',
            'interlocutor' => 'PaylineWebPayment\\StructType\\Interlocutor',
            'option' => 'PaylineWebPayment\\StructType\\Option',
            'iban' => 'PaylineWebPayment\\StructType\\Iban',
            'rib' => 'PaylineWebPayment\\StructType\\Rib',
            'bankAccount' => 'PaylineWebPayment\\StructType\\BankAccount',
            'bankAccountData' => 'PaylineWebPayment\\StructType\\BankAccountData',
            'technicalData' => 'PaylineWebPayment\\StructType\\TechnicalData',
            'contract' => 'PaylineWebPayment\\StructType\\Contract',
            'customPaymentPageCode' => 'PaylineWebPayment\\StructType\\CustomPaymentPageCode',
            'ticketSend' => 'PaylineWebPayment\\StructType\\TicketSend',
            'pointOfSell' => 'PaylineWebPayment\\StructType\\PointOfSell',
            'contracts' => 'PaylineWebPayment\\StructType\\Contracts',
            'customPaymentPageCodeList' => 'PaylineWebPayment\\StructType\\CustomPaymentPageCodeList',
            'virtualTerminal' => 'PaylineWebPayment\\StructType\\VirtualTerminal',
            'functions' => 'PaylineWebPayment\\StructType\\Functions',
            'virtualTerminalFunction' => 'PaylineWebPayment\\StructType\\VirtualTerminalFunction',
            'functionParameter' => 'PaylineWebPayment\\StructType\\FunctionParameter',
            'cheque' => 'PaylineWebPayment\\StructType\\Cheque',
            'contribution' => 'PaylineWebPayment\\StructType\\Contribution',
            'associatedTransactions' => 'PaylineWebPayment\\StructType\\AssociatedTransactions',
            'associatedTransactionsList' => 'PaylineWebPayment\\StructType\\AssociatedTransactionsList',
            'statusHistory' => 'PaylineWebPayment\\StructType\\StatusHistory',
            'statusHistoryList' => 'PaylineWebPayment\\StructType\\StatusHistoryList',
            'paymentAdditional' => 'PaylineWebPayment\\StructType\\PaymentAdditional',
            'paymentAdditionalList' => 'PaylineWebPayment\\StructType\\PaymentAdditionalList',
            'CustomerTransHist' => 'PaylineWebPayment\\StructType\\CustomerTransHist',
            'CustomerTrans' => 'PaylineWebPayment\\StructType\\CustomerTrans',
            'PaymentMeansTransHist' => 'PaylineWebPayment\\StructType\\PaymentMeansTransHist',
            'PaymentMeansTrans' => 'PaylineWebPayment\\StructType\\PaymentMeansTrans',
            'AlertsTransHist' => 'PaylineWebPayment\\StructType\\AlertsTransHist',
            'AlertsTrans' => 'PaylineWebPayment\\StructType\\AlertsTrans',
            'creditor' => 'PaylineWebPayment\\StructType\\Creditor',
            'subMerchant' => 'PaylineWebPayment\\StructType\\SubMerchant',
            'media' => 'PaylineWebPayment\\StructType\\Media',
            'routingRule' => 'PaylineWebPayment\\StructType\\RoutingRule',
            'threeDSInfo' => 'PaylineWebPayment\\StructType\\ThreeDSInfo',
            'browser' => 'PaylineWebPayment\\StructType\\Browser',
            'sdk' => 'PaylineWebPayment\\StructType\\Sdk',
            'merchantAuthentication' => 'PaylineWebPayment\\StructType\\MerchantAuthentication',
            'sdkChallenge' => 'PaylineWebPayment\\StructType\\SdkChallenge',
            'reattempt' => 'PaylineWebPayment\\StructType\\Reattempt',
        ];
    }
}
